openapi: 3.0.3
info:
  title: UBL ID — People · LLM · Apps
  version: "0.1.0"
servers:
  - url: http://localhost:8080
paths:
  /id/register/begin:
    post:
      summary: Begin WebAuthn registration (people)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username: { type: string }
      responses:
        "200":
          description: challenge
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebAuthnBegin"
  /id/register/finish:
    post:
      summary: Finish WebAuthn registration (people)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterFinish"
      responses:
        "201": { description: created }
        "409": { description: challenge expired/used }
  /id/login/begin:
    post:
      summary: Begin WebAuthn login (people)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username: { type: string }
      responses:
        "200":
          description: challenge
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebAuthnBegin"
  /id/login/finish:
    post:
      summary: Finish WebAuthn login (people)
    # returns session cookie httpOnly
      responses:
        "200": { description: session established }
        "409": { description: challenge expired/used }
  /id/agents:
    post:
      summary: Create agent (LLM/App) with Ed25519 public key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAgent"
      responses:
        "201":
          description: agent created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Agent"
  /id/agents/{sid}/asc:
    post:
      summary: Issue Agent Signing Certificate (ASC)
      parameters:
        - in: path
          name: sid
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IssueAsc"
      responses:
        "201":
          description: ASC issued
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Asc"
  /id/agents/{sid}/rotate:
    post:
      summary: Rotate agent key (publishes new pubkey and revokes previous)
      parameters:
        - in: path
          name: sid
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RotateKey"
      responses:
        "200": { description: rotated }
  /id/sessions/ict/begin:
    post:
      summary: Begin Intent Context Temporal Escrow (ICTE)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IcteBegin"
      responses:
        "200": { description: ict started }
  /id/sessions/ict/finish:
    post:
      summary: Finish ICTE (binds to subject and policy version)
      responses:
        "200": { description: ict established }
  /id/whoami:
    get:
      summary: Current subject + sessions
      responses:
        "200":
          description: info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WhoAmI"
components:
  schemas:
    WebAuthnBegin:
      type: object
      properties:
        challenge: { type: string, description: base64url }
        rpId: { type: string }
        user:
          type: object
          properties:
            id: { type: string, description: base64url 32 bytes }
            name: { type: string }
            displayName: { type: string }
    RegisterFinish:
      type: object
      properties:
        id: { type: string }
        rawId: { type: string }
        response:
          type: object
          properties:
            attestationObject: { type: string }
            clientDataJSON: { type: string }
        type: { type: string }
        clientExtensionResults: { type: object }
    CreateAgent:
      type: object
      required: [kind, display_name, public_key]
      properties:
        kind: { type: string, enum: ["llm","app"] }
        display_name: { type: string }
        public_key: { type: string, description: "hex Ed25519" }
        meta:
          type: object
          properties:
            tenant: { type: string }
            device_tag: { type: string, description: "ex: LAB512, iPhoneRunner" }
    Agent:
      type: object
      properties:
        sid: { type: string }
        kind: { type: string }
        public_key: { type: string }
        created_at: { type: string }
    IssueAsc:
      type: object
      required: [scopes, ttl_minutes]
      properties:
        scopes:
          type: object
          properties:
            containers: { type: array, items: { type: string } }
            intent_classes: { type: array, items: { type: string, enum: ["Observation","Conservation","Entropy","Evolution"] } }
            max_delta: { type: string, description: "i128 string (absolute per commit)" }
        ttl_minutes: { type: integer, minimum: 1, maximum: 1440 }
    Asc:
      type: object
      properties:
        asc_id: { type: string }
        sid: { type: string }
        public_key: { type: string }
        scopes: { type: object }
        not_before: { type: string }
        not_after: { type: string }
        signature: { type: string, description: "Ed25519 signature by UBL ID authority" }
    RotateKey:
      type: object
      required: [new_public_key]
      properties:
        new_public_key: { type: string, description: "hex Ed25519" }
    IcteBegin:
      type: object
      required: [scope, ttl_minutes]
      properties:
        scope:
          type: object
          properties:
            containers: { type: array, items: { type: string } }
            max_delta: { type: string }
        ttl_minutes: { type: integer, minimum: 1, maximum: 30 }
    WhoAmI:
      type: object
      properties:
        subject:
          type: object
          properties:
            sid: { type: string }
            kind: { type: string, enum: ["person","llm","app"] }
            display_name: { type: string }
        sessions:
          type: array
          items: { type: object }
